

is_debug: true 
# for running app on port and socket
listen:
  type: port 
  # type: sock 
  # bind_id: 0.0.0.0
  port: 1234

mongodb:
  host: localhost
  port: 27017
  database: user-service
  auth_db: 
  username: 
  password: 
  collection: users

storage: 
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
